# .github/workflows/docs.yml
name: Documentation

on:
  push:
    branches: [ master ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        cache: 'pip'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install sphinx sphinx-rtd-theme
        pip install -e . || echo "Package install failed, continuing without it"

    - name: Build documentation
      run: |
        cd docs
        make html
        echo "Build completed successfully!"

    - name: Add .nojekyll file
      run: |
        mkdir -p docs/_build/html
        touch docs/_build/html/.nojekyll
        echo ".nojekyll file created"

    - name: Setup Pages
      uses: actions/configure-pages@v4

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: docs/_build/html

    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4

    - name: 📍 Display deployment information
      run: |
        echo "🎉 Documentation deployed successfully!"
        echo ""
        echo "📍 Your documentation is available at:"
        echo "🔗 https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/"
        echo ""
        echo "ℹ️  It may take a few minutes for changes to be visible."
        echo "ℹ️  If you don't see updates, try clearing your browser cache."
