# .github/workflows/docs-minimal.yml
# Ultra-minimal workflow for Sphinx documentation

name: Build Docs

on:
  push:
    branches: [ master ]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  docs:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - run: |
        pip install -r requirements.txt
        pip install -e .
        cd docs && make html
        touch _build/html/.nojekyll

    - uses: actions/configure-pages@v4
    - uses: actions/upload-pages-artifact@v3
      with:
        path: docs/_build/html
    - uses: actions/deploy-pages@v4
      id: deployment
